services:
  controller:
    image: hivemind:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: hivemind-config
        target: /app/config/hivemind-config.yml
        mode: 0444
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - hivemind

networks:
  hivemind:
    driver: overlay

configs:
  hivemind-config:
    file: ./hivemind-config.yml
